development:
  adapter: postgresql
  database: prelaunchr
  host: localhost
  username: postgres
  password: postgres

test:
  adapter: postgresql
  database: prelaunchr
  host: localhost

production:
  adapter: postgresql
  database: prelaunchr
  username: twealr_landing
  host: localhost
  password: VXnosYLYu4
